### ISSUE TITLE
Errors when performing clean build of LCGEO from Master

### ISSUE THREAD

**Issue by rashaveraka** [iLCSoft/lcgeo#178]
!!!IMPORTANT!!!: To facilitate faster and easier response to your issue please provide in addition to the description of the issue also the following information

 - OS version: SLC6
 - Compiler version:  GCC 4.9
 - Package version: Master branch of LCGEO
 - Reproduced by: 

Download lcgeo from GitHub (delete any older installation of lcgeo, if the case)

git clone https://github.com/iLCSoft/lcgeo.git

Configure ILCSoft v01-19-04 and compile lcgeo

cd lcgeo
mkdir build 
cd build
source /cvmfs/ilc.desy.de/sw/x86_64_gcc49_sl6/v01-19-04/init_ilcsoft.sh
cmake -DCMAKE_CXX_COMPILER=`which g++` -DCMAKE_C_COMPILER=`which gcc` -C $ILCSOFT/ILCSoft.cmake ..
make -w -j4 install

 - Input: N/A
 - Output: 

[ross.mccoy@hep-sid build]$ make -w -j4 install
make: Entering directory `/home/ross.mccoy/lcgeoTEST/lcgeo/build'
make[1]: Entering directory `/home/ross.mccoy/lcgeoTEST/lcgeo/build'
make[2]: Entering directory `/home/ross.mccoy/lcgeoTEST/lcgeo/build'
make[2]: Entering directory `/home/ross.mccoy/lcgeoTEST/lcgeo/build'
make[2]: Entering directory `/home/ross.mccoy/lcgeoTEST/lcgeo/build'
make[2]: Leaving directory `/home/ross.mccoy/lcgeoTEST/lcgeo/build'
make[2]: Leaving directory `/home/ross.mccoy/lcgeoTEST/lcgeo/build'
make[2]: Leaving directory `/home/ross.mccoy/lcgeoTEST/lcgeo/build'
make[2]: Entering directory `/home/ross.mccoy/lcgeoTEST/lcgeo/build'
[  1%] Built target BeamCalZtest
[  3%] Built target TestSensThickness
make[2]: Entering directory `/home/ross.mccoy/lcgeoTEST/lcgeo/build'
[  4%] Building CXX object CMakeFiles/lcgeoG4.dir/plugins/CaloPreShowerSDAction.cpp.o
make[2]: Leaving directory `/home/ross.mccoy/lcgeoTEST/lcgeo/build'
make[2]: Entering directory `/home/ross.mccoy/lcgeoTEST/lcgeo/build'
[  7%] Building CXX object CMakeFiles/lcgeo.dir/detector/tracker/TPC10_geo.cpp.o
[  7%] Building CXX object CMakeFiles/lcgeo.dir/detector/tracker/TrackerEndcap_o1_v01_geo.cpp.o
[  7%] Building CXX object CMakeFiles/lcgeo.dir/detector/tracker/TrackerBarrel_o1_v05_geo.cpp.o
/home/ross.mccoy/lcgeoTEST/lcgeo/detector/tracker/TPC10_geo.cpp: In function ‘dd4hep::Ref_t create_element(dd4hep::Detector&, xml_h, dd4hep::SensitiveDetector)’:
/home/ross.mccoy/lcgeoTEST/lcgeo/detector/tracker/TPC10_geo.cpp:463:99: error: ‘Unbounded’ is not a member of ‘dd4hep::rec::SurfaceType’
     VolCylinder surf( upperlayerLog , SurfaceType(SurfaceType::Sensitive, SurfaceType::Invisible, SurfaceType::Unbounded ) ,  (padHeight/2.0) ,  (padHeight/2.0) ,o ) ;
                                                                                                   ^
/home/ross.mccoy/lcgeoTEST/lcgeo/detector/tracker/TPC10_geo.cpp:621:12: error: ‘dd4hep::rec::FixedPadSizeTPCData’ has no member named ‘zMinReadout’
   tpcData->zMinReadout = dz_Cathode/2.0;
            ^
/home/ross.mccoy/lcgeoTEST/lcgeo/plugins/CaloPreShowerSDAction.cpp: In member function ‘void dd4hep::sim::Geant4SensitiveAction<T>::defineCollections() [with T = dd4hep::sim::CalorimeterWithPreShowerLayer]’:
/home/ross.mccoy/lcgeoTEST/lcgeo/plugins/CaloPreShowerSDAction.cpp:39:19: warning: declaration of ‘name’ shadows a member of 'this' [-Wshadow]
       std::string name = m_sensitive.readout().name() ;
                   ^
/home/ross.mccoy/lcgeoTEST/lcgeo/plugins/CaloPreShowerSDAction.cpp: In member function ‘bool dd4hep::sim::Geant4SensitiveAction<T>::process(G4Step*, G4TouchableHistory*) [with T = dd4hep::sim::CalorimeterWithPreShowerLayer]’:
/home/ross.mccoy/lcgeoTEST/lcgeo/plugins/CaloPreShowerSDAction.cpp:89:29: error: ‘BitFieldCoder’ in namespace ‘dd4hep::DDSegmentation’ does not name a type
       const DDSegmentation::BitFieldCoder& bc = *idspec.decoder() ;
                             ^
/home/ross.mccoy/lcgeoTEST/lcgeo/plugins/CaloPreShowerSDAction.cpp:90:19: error: ‘bc’ was not declared in this scope
       int layer = bc.get(cell, "layer") ;
                   ^
make[2]: *** [CMakeFiles/lcgeo.dir/detector/tracker/TPC10_geo.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [CMakeFiles/lcgeoG4.dir/plugins/CaloPreShowerSDAction.cpp.o] Error 1
make[2]: Leaving directory `/home/ross.mccoy/lcgeoTEST/lcgeo/build'
make[1]: *** [CMakeFiles/lcgeoG4.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[2]: Leaving directory `/home/ross.mccoy/lcgeoTEST/lcgeo/build'
make[1]: *** [CMakeFiles/lcgeo.dir/all] Error 2
make[1]: Leaving directory `/home/ross.mccoy/lcgeoTEST/lcgeo/build'
make: *** [all] Error 2
make: Leaving directory `/home/ross.mccoy/lcgeoTEST/lcgeo/build'

 - Goal: Clean install and build of LCGEO

**Comment by rete** [comment]
Hi,

you are using the ilcsoft version v01-19-04 and DD4hep now includes new needed functionalities to compile the current HEAD of lcgeo. See DD4hep PR  [#244](https://github.com/AIDASoft/DD4hep/pull/244) and also lcgeo PR #173. 
Please update your DD4hep version, try to re-compile lcgeo and tell us if the problem persists.

Cheers, RE

**Comment by rete** [comment]
Hi !
Should we close this issue ?

**Comment by rashaveraka** [comment]
I apologize, I have been travelling and did not see this.

Please close this issue, I was able to build LCGEO after rebuilding DD4HEP.

Thanks,
Ross McCoy
UT-Arlington

**Comment by rete** [comment]
@iLCSoft/developers We can close this issue ( I can't....)
