### ISSUE TITLE
Failing test #3: t_test_SiD_o2_v02

### ISSUE THREAD

**Issue by gaede** [iLCSoft/lcgeo#184]
We have failing tests for SiD:  [https://travis-ci.org/iLCSoft/lcgeo/builds](https://travis-ci.org/iLCSoft/lcgeo/builds).

These seem to be related due to: https://github.com/AIDASoft/DD4hep/pull/258.

The test did not fail on my Mac before updating to DD4hep#258 and it does not fail on SL6 gcc49 with the latest release of DD4hep [https://github.com/AIDASoft/DD4hep/tree/v01-05](https://github.com/AIDASoft/DD4hep/tree/v01-05).

After updating DD4hep and lcgeo the test failed once on my Mac - however repeating it several times it did not fail again ...

@petricm could thhis be related to the strange failing tests for DD4hep that you reported in the last DD4hep meeting ?

**Comment by petricm** [comment]
@gaede what I reported was not merged (AIDASoft/DD4hep#264) as I am still investigating. There was no change to the CI for quite some time. 

The sporadic fails are probably due to test shooting the particle into a different direction each time the test is executed.

**Comment by shaojunlu** [comment]
Dear All,
https://github.com/iLCSoft/lcgeo/blob/master/SiD/compact/SiD_o2_v02/BeamCal_o2_v02_00.xml#L8
This line 18 is the encoding string for SiD_o2_v02 BeamCal.

https://travis-ci.org/iLCSoft/lcgeo/jobs/306287753#L838

The failing is about try to save "-10" of CartesianGridXY into "x".

https://travis-ci.org/iLCSoft/lcgeo/jobs/306287753#L1831
https://travis-ci.org/iLCSoft/lcgeo/jobs/306287753#L1832
Is this position is in the BeamCal of Sid_o2_v02?

@protopopescu 
This should be the right encoding string for your BeamCal.
<id>system:8,barrel:3,layer:8,slice:5,x:32:-16,y:-16</id>

**Comment by protopopescu** [comment]
Thanks Shaojun! Please see PR #185

**Comment by protopopescu** [comment]
I am currently working on SiD_o2_v03, and Sid_o2_v02 is actually no longer maintained as it will be soon obsolete.
