### ISSUE TITLE
The ZPlanarTracker constructor does not set det_type flags.

### ISSUE THREAD

**Issue by StrahinjaLukic** [iLCSoft/lcgeo#192]
The vertex barrel in CLIC_o3_v13 is of type ZPlanarTracker. The corresponding constructor does not set the det_type flags even if they are present in the xml file. 

- OS version: Ubuntu linux 14.04
- Compiler version: GCC 6.4
- Package version: tag v01-19-05
- Reproduced by: 
    1. Run the reconstruction with, e.g. `CLICPerformance/v02-00-00/examples/clicReconstruction.xml`
    2. Run `SiTracker_dEdxProcessor` (from MarlinReco/Analysis/SiPID/). This processor uses detector-type flags to determine whether a tracker element is of type barrel or endcap. If the flag is not set, the processor streamlogs an error (and later crashes because it misses the vertex barrel, which is a different issue...)

 - Input: [SiTrack_dEdx.xml.txt](https://github.com/iLCSoft/lcgeo/files/1542540/SiTrack_dEdx.xml.txt)
 - Output: [marlinout.txt](https://github.com/iLCSoft/lcgeo/files/1542574/marlinout.txt)
 - Goal: Use detector type flags in a processor.

**Comment by petricm** [comment]
The [DetectorTypeFlag](https://dd4hep.web.cern.ch/dd4hep/reference/namespacedd4hep_1_1xml.html#ac4edc8641d0a286a50e99aa2faf065b2) are set by the invocation of  `dd4hep::xml::setDetectorTypeFlag` which is present in in [ZPlanarTracker_geo.cpp](https://github.com/iLCSoft/lcgeo/blob/master/detector/tracker/ZPlanarTracker_geo.cpp#L72) and [TrackerBarrel_o1_v05_geo.cpp](https://github.com/iLCSoft/lcgeo/blob/master/detector/tracker/TrackerBarrel_o1_v05_geo.cpp#L70). They are also defined in the `xml` of CLIC_o3_v13 [here](https://github.com/iLCSoft/lcgeo/blob/master/CLIC/compact/CLIC_o3_v14/InnerTracker_o2_v06_01.xml#L103) and [here](https://github.com/iLCSoft/lcgeo/blob/master/CLIC/compact/CLIC_o3_v14/Vertex_o2_v06_01.xml#L76). How to you access the this information? Do you do something linke:
```cpp
      int  subdet   = m_encoder[lcio::LCTrackerCellID::subdet()];
      int  side     = m_encoder[lcio::LCTrackerCellID::side()];
      int  layer    = m_encoder[lcio::LCTrackerCellID::layer()];
      bool isEndcap = false;
      bool forward  = false;
      if (side != ILDDetID::barrel) {
        isEndcap = true;
        if (side == ILDDetID::fwd)
          forward = true;
      }
```

**Comment by StrahinjaLukic** [comment]
Hi Marko,

Yes, I know that the invocation of `dd4hep::xml::setDetectorTypeFlag` is present in `ZPlanarTracker_geo.cpp`. I have tried inserting short cout statements into `dd4hep::PluginRegistry::add()` ([here](https://github.com/AIDASoft/DD4hep/blob/17bf643b82fa2e859517919b91ef824f1d1adb0f/DDCore/include/DD4hep/Plugins.h#L139)) and into the static function `create_element()` from `ZPlanarTracker_geo.cpp` to verify that these parts of code get actually executed. `dd4hep::PluginRegistry::add()` shouts back correctly and outputs the string id for all detector components it registers, including "ZPlanarTracker". But `create_element()` from `ZPlanarTracker_geo.cpp` remains "silent". I am wondering if it is invoked at all, although I do not see in the code why it would not be.

As to your question how I access the type flags, I directly use `dd4hep::DetElement::typeFlag()`. Following is an excerpt from the code:
```
LayerFinder::LayerFinder(EVENT::StringVec _collectionNames, dd4hep::Detector& theDetector,
                          FloatVec sensThickCheatVals, int elementMask) :
  knownDetectors()
{
  const std::vector< dd4hep::DetElement > &detElements = theDetector.detectors("tracker", true);
  ...
  for(unsigned i=0; i<detElements.size(); i++) {
  ...
  int tf = detElements.at(i).typeFlag();
  ...
  ```
For all other tracker detectors except for the vertex barrel `tf` gets the correct value composed of the flags present in the respective xml files. Only for the vertex barrel, `tf` is zero.

Let me know if there is any other info I can supply to help solve this.

In the meantime I am adapting the processor to test for the presence of the ZPlanarData (and ZDiskPetalsData) extensions in the DetElement instead of using the type flags. This is what the processor directly uses and is probably a more robust approach for this particular processor. But the type flags are probably still needed elsewhere.

**Comment by andresailer** [comment]
When I add this to TestSensThickness I get the Barrel/Tracker/Pixel info for VertexBarrel
```c++
  const std::vector< dd4hep::DetElement > &detElements = lcdd.detectors("tracker", true);
  for(unsigned i=0; i<detElements.size(); i++) {
    auto const& detElement = detElements.at(i);
    std::cout << detElement.name() << ": " << dd4hep::DetType(detElement.typeFlag())  << std::endl;
   }
```

```
InnerTrackerBarrel: DetType( 0x11) : TRACKER, BARREL,
InnerTrackerEndcap: DetType( 0x9) : TRACKER, ENDCAP,
OuterTrackerBarrel: DetType( 0x11) : TRACKER, BARREL,
OuterTrackerEndcap: DetType( 0x9) : TRACKER, ENDCAP,
VertexBarrel: DetType( 0x151) : TRACKER, BARREL, VERTEX, PIXEL,
VertexEndcap: DetType( 0x149) : TRACKER, ENDCAP, VERTEX, PIXEL,
```

**Comment by StrahinjaLukic** [comment]
Hm. Strange. I must have a bug somewhere else, then. Ok, closing this now and will try to figure out later what the problem was.
