### ISSUE TITLE
Allow to write event parameters for every event in DDSim

### ISSUE THREAD

**Issue by gaede** [iLCSoft/lcgeo#194]
We need the possibility to write parameters to the `LCEvent` for every event, e.g. the `processID`, cross section, polarization etc. Implementation should be similar to the `RunHeader`.

If the parameters are present in the LCIO input file, they should be copied to the output file.

Depends on https://github.com/AIDASoft/DD4hep/issues/285

**Comment by rete** [comment]
See also [AIDASoft/DD4hep#309](https://github.com/AIDASoft/DD4hep/issues/309)

**Comment by rete** [comment]
Solved in #196 and [AIDASoft/DD4hep#321](https://github.com/AIDASoft/DD4hep/pull/321)
