### ISSUE TITLE
Too few backscattering particles from BeamCal in the simulation of ILD machine backgrounds

### ISSUE THREAD

**Issue by StrahinjaLukic** [iLCSoft/lcgeo#195]
Hi all,

I am running simulations of ILD machine backgrounds using ILD_o1_v05 detector model and guinea-pig Beamstrahlung (eepair) files as input. A very important detail of this study is the backscattering of Beamstrahlung from BeamCal. In the simulation I am observing an extremely low number of secondary particle vertices in the BeamCal region - only about 5-10 vertices per BX at z>3m, depending on the choice of magnetic fields. At the same time, the number of SimCalorimeterHits  at z>3m is 1.0-1.3 million/BX. Of this, over 700k simCaloHits are in BeamCal.

I am using the LCTuple Marlin processor to analyse the detector hits and MC particle vertices.

In all previous similar studies, particles backscattered from BeamCal were a major source of occupancies in the vertex detector, so one would expect to see far more backscattering.

So far I tried modifying the DDSim parameters `SIM.part.keepAllParticles`, `SIM.part.minimalKineticEnergy` (down to 1 KeV), and `SIM.filter.tracker` to `"edep0"` but there is no significant change in the above numbers. 

Am I missing something obvious? Do you have a recommendation how to run ddsim to get a realistic picture of beamstrahlung backscattering from BeamCal?

Thanks for any hints,
Strahinja

 - OS version: SLC6
 - Compiler version: e.g GCC 4.9
 - Package version: /cvmfs/ilc.desy.de/sw/x86_64_gcc49_sl6/v01-19-05/lcgeo/v00-15-03/
 - Reproduced by: 
```
    source /cvmfs/ilc.desy.de/sw/x86_64_gcc49_sl6/v01-19-05/init_ilcsoft.sh
    ddsim --inputFiles '/pnfs/desy.de/ilc/prod/ilc/mc-dbd/generated/500-TDR_ws/eepairs/E500-TDR_ws.PBeamstr-pairs.GGuineaPig-v1-4-4.I230000.'${number}'.pairs' \
    --outputFile=something.slcio --compactFile ILD_o1_v05.xml --steeringFile=ddsim_steer.py \
    --guineapig.particlesPerEvent=1000 
``` 

[ddsim_steer.py.zip](https://github.com/iLCSoft/lcgeo/files/1642620/ddsim_steer.py.zip)
[ILD_o1_v05.zip](https://github.com/iLCSoft/lcgeo/files/1642623/ILD_o1_v05.zip)

**Comment by StrahinjaLukic** [comment]
BeamCal08.xml contains the following in its `<detector ...>` tag: `insideTrackingVolume="false"`. Does this in any way affect the creation/tracking of secondaries?

**Comment by StrahinjaLukic** [comment]
BTW, how (and where) exactly is the tracking volume defined in ddsim? I am reading Frank's presentation od ddsim from LCWS14, particularly the following:

**New particles, created in simulation are added to the MCParticle list if:**
  * they are created (decay, interaction,...) **inside the tracking volume**
  * and their energy E > E_cut
    * e.g. low energy delta electron are not created, but Bremsstrahlung photons are
    * decays in flight (K0_s) are always created

**Shower particles are not created**, hits are assigned to parent  particle (the one entering the calorimeter)
exceptions:
  * particles **scattered back into the tracking volume**
  * default shower mode is activated for dedicated studies

So it seems that, if I can make sure that the tracking volume extends along z up to the boundary with the BeamCal absorbers, I could expect to have the backscattered particles created and added to the MCParticle collection. Thus my question: Where in the xml or the steering files (or elsewhere) is the tracking volume defined?

**Comment by petricm** [comment]
The tracking volume in the compact file as:
https://github.com/iLCSoft/lcgeo/blob/master/CLIC/compact/CLIC_o3_v14/CLIC_o3_v14.xml#L179-L180

We suggest that you, disable ECAL, HCAL and everything outwards (to speed up things) and then extend the tracking volume to include LumiCal and BeamCal and retry your test.

**Comment by StrahinjaLukic** [comment]
Thanks! 
Now, by "disabling" the calorimeters, do you mean comment them out in the main .xml file, or something else?

**Comment by petricm** [comment]
yes, just remove the include statement from xml.

**Comment by StrahinjaLukic** [comment]
What is the effect of `insideTrackingVolume="false"` for a detector that is geometrically located within the tracking region? Is the volume of this detector locally excluded from the tracking region?

**Comment by gaede** [comment]
This seems to be only a redundant attribute - you can ask if a Detector `isInsideTrackingVolume()`.
Actually we should think about removing this to avoid confusion.

**Comment by StrahinjaLukic** [comment]
Ok, I am now getting ~5 orders of magnitude more vertices in BeamCal. I will report back with more details when I have done a full test.

**Comment by rete** [comment]
@StrahinjaLukic What is the current status of this issue ?

**Comment by StrahinjaLukic** [comment]
Resolved. Thanks for reminding me.
