### ISSUE TITLE
Implement ILD detector models with field maps

### ISSUE THREAD

**Issue by gaede** [iLCSoft/lcgeo#198]
We need to create ILD detector models with realistic field maps, that are otherwise identical to the standard ones, ILD_ls5_o123_v02, e.g using _v03 and _v04 for w/ and w/o anti-DID.
Initially this needs to be done for the large detectors only.

- The solenoid and anti-DID implementation should be like here:
https://github.com/iLCSoft/lcgeo/blob/master/ILD/compact/ILD_o1_v05/ILD_o1_v05.xml#L594-L627

- we also need additional B-fields for the downstream magnets, QD0 et al

**Comment by danieljeans** [comment]
I assume that an ideal quadrupole field in the region of qd0 would be a sufficiently good approximation for now. It should be aligned with the incoming beamline.

in principle dd4hep knows about multipole fields:
https://dd4hep.web.cern.ch/dd4hep/reference/classdd4hep_1_1MultipoleField.html ,
but it's not obvious to me how to specify such a field in the xml description.

an less elegant alternative would be to include this field into the fieldmap by brute force.

**Comment by petricm** [comment]
@danieljeans you can add fields like this

https://github.com/AIDASoft/DD4hep/blob/master/examples/LHeD/compact/compact_Lhe_dip_sol_big_sol_ell.xml#L1922-L1951

should also work for quadrupole

**Comment by petricm** [comment]
And the definitions of the coefficients are here

https://github.com/AIDASoft/DD4hep/blob/e744354ef544b066e4e5a663d695429e8521e50a/DDCore/src/FieldTypes.cpp

**Comment by gaede** [comment]
Closed via #212
