### ISSUE TITLE
Wget certificate in TravisCI (ecsft.cern.ch)

### ISSUE THREAD

**Issue by rete** [iLCSoft/lcgeo#221]
It seems that our TravisCI is broken in all packages: 
```shell
wget https://ecsft.cern.ch/dist/cvmfs/cvmfs-release/cvmfs-release-latest_all.deb
--2018-06-20 08:03:13--  https://ecsft.cern.ch/dist/cvmfs/cvmfs-release/cvmfs-release-latest_all.deb
Resolving ecsft.cern.ch (ecsft.cern.ch)... 188.184.161.78
Connecting to ecsft.cern.ch (ecsft.cern.ch)|188.184.161.78|:443... connected.
ERROR: cannot verify ecsft.cern.ch's certificate, issued by ‘/C=GB/ST=Greater Manchester/L=Salford/O=COMODO CA Limited/CN=COMODO RSA Domain Validation Secure Server CA’:
  Unable to locally verify the issuer's authority.
To connect to ecsft.cern.ch insecurely, use `--no-check-certificate'.

The command "wget https://ecsft.cern.ch/dist/cvmfs/cvmfs-release/cvmfs-release-latest_all.deb" failed and exited with 5 during .

Your build has been stopped.
```
I'm not expert in certificates, but it seems that we can use the `--no-check-certificate` option to make `wget` happy.

@andresailer @gaede Is this a reasonable solution ? If yes, we have to update all our packages ...

**Comment by andresailer** [comment]
@rete Yes, this is probably the easiest solution. It might be that curl would work instead of wget.

**Comment by gaede** [comment]
It worked - at least for lcio, where I simply added it to the PR: 
https://github.com/iLCSoft/LCIO/pull/48/commits/1132d8e2754579001105137fbd8a94e3e9085a6e

So we could simply add it to all future PRs - or ask the authors to add it, if the CI fails...

**Comment by andresailer** [comment]
It seems the problem has fixed itself, e.g. this KiTrackMarlin ran 2 days ago without problems:
https://travis-ci.org/iLCSoft/KiTrackMarlin/jobs/398458514

**Comment by rete** [comment]
Self-solving bug... We should have more like this
