### ISSUE TITLE
Missing hits in ILD TPC

### ISSUE THREAD

**Issue by gaede** [iLCSoft/lcgeo#227]
We observe a significant drop of *number of TPC SimTrackerHits* for single muons (20 GeV) at cos(th) ~ 0.8 ( ~36.5 deg) in the ILD_l5_v02 models.

The reason is, that with the activation of user limits in DD4hep, we have a max_step_size of 5mm that causes hits to end just at the volume boundary (gas tube with 3mm thickness).  Then the subsequent step into the next volume is missed....

![muon_20gev_36deg_nsth_vs_theta](https://user-images.githubusercontent.com/14929044/42814637-1f50a0a2-89c5-11e8-9e5a-1fc96844ff5b.png)

![tpc_simhits_35deg_muon](https://user-images.githubusercontent.com/14929044/42814621-107e227a-89c5-11e8-8aee-62bc800aa8c4.png)

**Comment by shaojunlu** [comment]
@danieljeans 
I have generated a PR https://github.com/iLCSoft/ILDConfig/pull/89 in ILDConfig with updated steering file to fix this issue. Would you please review this PR. Thanks.

**Comment by ueinhaus** [comment]
Confirmed this issue with the dE/dx processor, and excluded tracks in that angular range as a workaround to 'cure' it. Details
[here](https://github.com/iLCSoft/lcgeo/files/2201774/2018_07_23_Analysis_Meeting.pdf).
