### ISSUE TITLE
Multisegmentation not able to use "layer" for key

### ISSUE THREAD

**Issue by linghuiliu** [iLCSoft/lcgeo#230]
Environment: naf-ilc.desy.de, ILCSOFT v02-00-01 and v02-00-02 (lcgeo v00-16-01 and v00-16-03)

Tried to introduce multisegmentation in SHcalSc04_Barrel_v04.xml by layer as:
```xml
% <readouts>
%    <readout name="HcalBarrelReadout">
%      <segmentation   type="MultiSegmentation"  key="layer">
%        <segmentation name="ScigridInnerLayer"  type="CartesianGridXY"    key_min="0x1" key_max="24"    grid_size_x="30.0*mm" grid_size_y="30.0*mm" />
%        <segmentation name="ScigridOuterLaye"   type="CartesianGridXY"    key_min="25" key_max="0xFF" grid_size_x="60.0*mm" grid_size_y="60.0*mm" />
%      </segmentation>
%      <hits_collections>
%        <hits_collection name="HcalBarrelRegCollection" key="layer" key_min="0x1" key_max="0xFF"/>
%      </hits_collections>
%      <id>system:5,module:3,stave:4,tower:5,layer:6,slice:4,x:32:-16,y:-16</id>
%    </readout>
% </readouts>
```
ddsim complaint an error as:
**************************************************** 
*  A runtime error has occured :                     
*    MultiSegmentation: Invalid sub-segmentation identifier!
*  the program will have to be terminated - sorry.   
**************************************************** 

Using "slice" for the key instead of "layer" did work.

**Comment by rete** [comment]
Hi @linghuiliu 
Can you please post the complete compact XML and the corresponding C++ driver that you use for this sub-detector?
Also you can have a look to the [others multi-segmentation](https://github.com/iLCSoft/lcgeo/blob/master/ILD/compact/ILD_common_v02/SEcal06_hybrid_Endcaps.xml) sub-detector implementations.

**Comment by linghuiliu** [comment]
The full XML is below:
[SHcalSc04_Barrel_v04.txt](https://github.com/iLCSoft/lcgeo/files/2517460/SHcalSc04_Barrel_v04.txt)
It is loaded from ordinal ILD_l5_v02.xml.

I am not sure what C++ driver for the sub-detector is.
I'm using the detector model in ddsim.

**Comment by rete** [comment]
I don't understand what you are trying to achieve here. This sub-detector already have a multi-segmentation implemented. What is your goal ?

**Comment by linghuiliu** [comment]
Now I succeeded in simulating with the model by beginning the layer key_value from 0.
Thank you for the replies.
