### ISSUE TITLE
antiDID field map implementation (FieldMapXYZ)

### ISSUE THREAD

**Issue by luisaleperez** [iLCSoft/lcgeo#65]
Hello all,

I am working in the implementation of the antiDID field map and the production and study of machine induced background on ILC.

I would like to check that the solenoidal and antiDID fields get added up correctly. Is there a way to print out the total field requested at a given point?

Many thanks,

  Alejandro

**Comment by luisaleperez** [comment]
Hello all,

Here I would like to give you a bit more information about this issue.

Previously I was not able to create two DetectorMaps simultaneously inside the detector model xml file (see below),

https://github.com/luisaleperez/lcgeo/blob/AntiDIDFieldMap/ILD/compact/ILD_o1_v05/ILD_o1_v05.xml

As discussed in a previous issue,
https://github.com/AIDASoft/DD4hep/issues/136

by properly changing the names of the DetectorMap field ddsim was able to build both the solenoidal (FieldBrBz) and anti-DID (FieldXYZ) field maps. But I am not convinced that the code properly add them up. 

As a test I created a couple of artificial field maps for the solenoid and anti-DID which balanced each other, e.g., the solenoid and anti-DID fields were of 3.5 tesla along the Z-axis but with opposite directions. When I launch ddsim and then visualize the result of the simulation with ced2go I don't see straight tracks, but curved tracks as expected by the solenoidal field alone.

For each point where ddsim requested the calculation of the B-field, I printed out both the solenoidal and anti-DID fields and they give opposite values adding up to zero. An example of the print-out is below,

FieldMapBrBz:: 
(x,y,z)     = (-311.885,-24.0551,-112.282) cm
B(x,y,z)    = (0,0,3.5) tesla

FieldMapXYZ:: 
(x,y,z)     = (-311.885,-24.0551,-112.282) cm
B(x,y,z)    = (0,0,-3.5) tesla

This is why I am asking for a simple way to print out for each ddsim request the total field to check what the value is.

Many thanks,

  Alejandro

**Comment by andresailer** [comment]
maybe CED picks up the field incorrectly, or it is hardcoded, or it still comes from the GearFile?
Trye something like this
```
//includes
//#include "DD4hep/LCDD.h"
//#include "DD4hep/DD4hepUnits.h"

  const double pos[3]={0,0,0}; 
  double bFieldVec[3]={0,0,0}; 
  lcdd.field().magneticField(pos,bFieldVec); // get the magnetic field vector from DD4hep
  double _bField = bFieldVec[2]/dd4hep::tesla; // z component at (0,0,0)

```
combined with a small test program like https://github.com/iLCSoft/lcgeo/blob/master/lcgeoTests/src/TestSensThickness.cpp
to print out the field at different points of your choice ?

**Comment by luisaleperez** [comment]
Hi Andrea,

I am not following. Could you give me more details on where/how to include this code and compiled and how to run it. I don't know where should I include this code and how to compile it.

  Alejandro

**Comment by gaede** [comment]
@luisaleperez how did you see curved tracks in ced2go ? Did you look at the MCParticles or the SimHits ? As Andre suggested, if you call ced2go with a Gear file, the field used for _visualization_ will be the standard constant field in the tracking volume, you need to simulate high pt tracks, e.g. 2 GeV muons and then check if the resulting SimHits are on a straight line ...

**Comment by luisaleperez** [comment]
Yes, I saw curved tracks in ced2go. Yes, I looked at the MCParticles and so on using the dumpevent command.

Is there a way to visualize the simulation correctly using the right field?

Ok. I will simulate particles of 2 GeV electrons (using the GuineaPig file) and check the collections. I'll let you know my findings in a bit.

**Comment by gaede** [comment]
If you look at the SimTracker hits they should be on straight lines - as no field is used for the visualization. The MCParticles are drawn using the field (potentially the wrong one from Gear).

**Comment by gaede** [comment]
@all it would be nice to have a visualization of the B-field in DD4hep - any volunteers ?

**Comment by luisaleperez** [comment]
Does the SimTracker hits inclue the VXD hits?

**Comment by gaede** [comment]
yes.

**Comment by luisaleperez** [comment]
Ok. I did what you suggested me. I ran ddsim with a simple GuineaPig file,

[MyTest_v3.pairs.txt](https://github.com/iLCSoft/lcgeo/files/879127/MyTest_v3.pairs.txt)

As you can see, only two particles, one 2 GeV electron moving along the positive X-axis and one 2 GeV positron moving along the positive Y-axis. Both generated at the origin.

I ran ddsim as follows,
ddsim --inputFiles ./MyTest_v3.pairs --outputFile=./GuineaPig_1evt_TEST_v3.slcio --compactFile $lcgeo_DIR/ILD/compact/ILD_o1_v05/ILD_o1_v05_TEST.xml --steeringFile=./ddsim_steer_GuineaPig.py

where $lcgeo_DIR/ILD/compact/ILD_o1_v05/ILD_o1_v05_TEST.xml  is the xml file where the solenoidal and anti-DID field are opposite. You can see in the log file below the output of the ddsim command,
[log_v3.txt](https://github.com/iLCSoft/lcgeo/files/879135/log_v3.txt)

And in the log file below the output of doing: dumpevent GuineaPig_1evt_TEST_v3.slcio 1
[log_v3_dumpevent.txt](https://github.com/iLCSoft/lcgeo/files/879139/log_v3_dumpevent.txt)

For me it is not clear that the track are all moving in a straight line. Could you please point me to the right place to look?

Thanks




The

**Comment by luisaleperez** [comment]
Hi all,

I am not still sure that the total field is correct (in the case above very close to zero). I ask the question again: it is there a way to print out the total B-field?

Thanks,

  Alejandro

**Comment by gaede** [comment]
why don't you look at the simulated hits ced2go ? Use r-phi projection (key-f), the turn everything off (key-`) (potentially twice) and then show SimTrackerHIts only ( key-1).

**Comment by luisaleperez** [comment]
I just did what you told me and this is what I get,

![screenshot_guineapig_1evt_test_v3](https://cloud.githubusercontent.com/assets/25223578/24460015/49f3bbc6-149d-11e7-9185-2bfa8af8e252.png)

As you can see the track are curved, not straight as expected.

**Comment by andresailer** [comment]
https://gist.github.com/andresailer/3c6633d1941256ee6e06f9bc29055dd5
Something like this placed in lcgeoTests, change the CMakeLists.txt to make it compile as a binary

**Comment by luisaleperez** [comment]
Let me see if I understood you. You say to add a piece of code like this,

//includes
//#include "DD4hep/LCDD.h"
//#include "DD4hep/DD4hepUnits.h"

  const double pos[3]={0,0,0}; 
  double bFieldVec[3]={0,0,0}; 
  lcdd.field().magneticField(pos,bFieldVec); // get the magnetic field vector from DD4hep
  double _bField = bFieldVec[2]/dd4hep::tesla; // z component at (0,0,0)

in lcgeoTests/src/TestSensThickness.cpp and print out the B-field at different points of my choice. Then I have to modify the CMakeList.txt file of lcgeo to make an executable (or binary) for the lcgeoTest code. Is that right?

Well, some questions ...

1) I am not an expert. Could you give me more info about how I should modify CMakeList.txt file in order to produce the lcgeoTest executable?

2) When the executable is produced. How should I pass it the input xml file with the B-field configuration? Or, how should I run the executable, i.e. the command line and do I how to pass it the inputs?

Thanks,

  Alejandro

**Comment by gaede** [comment]
I have just created a PR for DD4hep (https://github.com/AIDASoft/DD4hep/pull/139) for a utility that dumps the B field.  You can either copy the code to your installation or wait until the CI builds have finished and the PR has been merged.

**Comment by gaede** [comment]
There was a bug in the field map code that prevented field overlaying - fixed in #67.

**Comment by luisaleperez** [comment]
Hello Frank,

Is this fix in lcgeo? If yes, can you instruct me to update my lcgeo version with the fix?

Many thanks,

  Alejandro

**Comment by gaede** [comment]
You simply do the usual commands for updating from git:
```
git checkout master
git pull
cd ./build
cmake ..
make install
```
