### ISSUE TITLE
Add correct tracker region to SiD models

### ISSUE THREAD

**Issue by gaede** [iLCSoft/lcgeo#81]
All models in lcgeo need to define the tracker region. This is needed for the MC-Truth handling in ddsim/DDG4. Basically hits outside the tracking volume (i.e. inside the calorimeter region) are assigned to the particle entering the calorimeter.
I have added an example to 
https://github.com/iLCSoft/lcgeo/blob/master/SiD/compact/SiD_o1_v01/SiD_o1_v01.xml#L122-L123
- these values need to be reviewed by  some one from SiD
- all other models need to have these parameters added
- **note: ddsim will exit if no tracker region is defined**

**Comment by protopopescu** [comment]
This is done starting from SiD_o2_v02. Models SiD_o1_v01 and SiD_o2_v01 are not used anymore - should I fix them nevertheless?

**Comment by petricm** [comment]
Actually the only model that is tested is [SiD_o1_v01](https://github.com/iLCSoft/lcgeo/blob/master/lcgeoTests/CMakeLists.txt#L24). If SiD_o1_v01 and SiD_o2_v01 are not used anymore remove them from the tests and add SiD_o2_v02 to the tests.

**Comment by protopopescu** [comment]
Ok, makes sense
